### ISSUE TITLE
Feature request: Use color-coding stacked bar graphs

### ISSUE THREAD

**Issue by linhtto** [mcndt/obsidian-toggl-integration#86]
- The pie chart has multiple colors matching different projects
- The bar chart has only one color, and it usually looks similar to one of the pie-chart colors, which can be confusing.
- Ideally, the bar charts should be stacked bar charts, with the same color codes for the different projects within each day/bar as used in the pie chart.

**Comment by mcndt** [comment]
Thanks for your feedback Linh!

I'll consider adding a more detailed bar chart if more users request this feature.

As to the bar chart color, it uses the "interactive" color of your Obsidian theme. So if it helps you in the mean time, you can easily customize this color to something that complements your project colors better. For example, you could use Obsidian's CSS snippets feature to customize the colors:

```css
.block-language-toggl {
  --interactive-accent: #00acc1 !important;
  --interactive-accent-hover: #00bcd4 !important;
}
```

Of course you can use any colors you like.

Hope that helps!
